name: Compile IDE

on: 
  push: 
    branches:
      - master
    paths:
      - 'IDE/src/**'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package | egrep -v "^\[INFO\].*?Download.*?http"
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: output-jar
        path: IDE/target/*.jar
